tenant_id                      = ""
resource_group_name            = ""
resource_group_location        = "westus2"
virtual_machine_admin_username = ""
virtual_machine_admin_password = ""
subnet_id                      = ""
security_group_id              = ""
